[package]
name = "dag-cbor"
version = "2.0.0"
description = "A Motoko library for encoding and decoding DAG-CBOR data structures."
repository = "https://github.com/edjcase/motoko_dagCbor"
keywords = ["dag", "cbor", "ipld", "encode", "decode"]
license = "MIT"

[dependencies]
core = "0.6.0"
cbor = "4.0.0"
cid = "1.0.1"
buffer = "0.0.1"

[dev-dependencies]
test = "2.1.1"

[toolchain]
moc = "0.14.14"
