[package]
name = "dag-cbor"
version = "0.0.1"
description = "A Motoko library for encoding and decoding DAG-CBOR data structures."
repository = "https://github.com/edjcase/motoko_dag_cbor"
keywords = ["dag", "cbor", "ipld", "encode", "decode"]
license = "MIT"

[dependencies]
base = "0.14.11"
new-base = "0.4.0"
cbor = "2.0.0"
cid = "0.0.1"

[dev-dependencies]
test = "2.1.1"

[toolchain]
moc = "0.14.11"
